### ISSUE TITLE
[JOSS Review] Repository License Issues

### ISSUE THREAD

**Issue by CameronDevine** [KCL-BMEIS/fri#17]
As part of the JOSS review, openjournals/joss-reviews#6138, this repository needs to have an OSI approved license. While this repository does have a license listed, I am worried about the license issues of including the KUKA FRI SDK in this repository.

This also appears to be related to #6 and #14. Please fix this issue using at least one of the methods suggested in your existing issues.

**Comment by mhubii** [comment]
hi @CameronDevine , just saw your first reviews. Thank you very much, I really appreciate it! Will try to fix those, so we can improve this software :)

**Comment by mhubii** [comment]
Putting for reference https://joss.readthedocs.io/en/latest/review_criteria.html#software-license

**Comment by mhubii** [comment]
added notice https://github.com/lbr-stack/fri/blob/fri-1.15/NOTICE
